version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '4306:3306'
    volumes:
      - './.data/mysql:/var/lib/mysql'
  php:
    container_name: php
    build:
      context: dockconfig/php
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/symfony_docker'
    depends_on:
      - database
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - '.:/var/www/symfony_docker'
      - './dockconfig/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - php
      - database
  rabbitmq:
    container_name: container_rabbitmq
    image: rabbitmq:3.7-management
    ports: [ 5672, 15672 ]
    depends_on:
      - php
      - database
      - nginx
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
